[project]
name = "mcp-fetch"
version = "0.1.5"
description = "Minimal MCP server providing a generic HTTP request tool with chunked responses and caching."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "fastmcp",
  "httpx>=0.28.1",
  "markdownify>=1.2.2",
  "playwright>=1.57.0",
]

[project.scripts]
mcp-fetch = "mcp_fetch.server:main"

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[build-system]
requires = ["hatchling>=1.24.2"]
build-backend = "hatchling.build"
